### PR TITLE
Cards have fixed height

### PR DESCRIPTION
**Pull request by zacharyjarnagin**
Added a CSS rule. Also I thought I created this pull request last night so sorry if it got denied and I just am delirious.

### CODE REVIEW

**Comment by lukesanantonio** [comment]
In the future, use the PR to reference the issue like this: Fixes #60

**Comment by lukesanantonio** [comment]
It seems like to achieve the result you're essentially just removing the wrapping `<span>` tag is that correct?

**Comment by zacharyjarnagin** [comment]
@lukesanantonio Not exactly. I removed the `<span> ` as it was creating a new grey outline around the rectangle with the fixed height of 200px. Removing span and placing the `<a>` tag within the `<div>` solved the issue. Would you like me to keep the `<span>` tag still?

**Comment by lukesanantonio** [comment]
Nope, I'm not attached to it I was just trying to figure out how this worked. At first glance I had completely missed the `min-height` style line, but I see it now. I'll finish review later today, but my initial thought is that it may be better to use em units here so that cards are sized relative to the font size (which may scale based on user accessibility settings).

**Comment by zacharyjarnagin** [comment]
That is a good point. I normally use `vh` or `vw` instead. Don't like relying on `px` so feel free to change it.

**Comment by zacharyjarnagin** [comment]
I looked at the conflict between div and my branch. It must have been what has been causing your error. If you could check again and let me know if it works as intended now that would be great!

**Comment by zacharyjarnagin** [comment]
My bad! Glad you fixed it, poor oversight by me.

**Pull request merged**
