### PR TITLE
Add hover shadow to curricula cards

### PR DESCRIPTION
**Pull request by lukesanantonio**
The little red dot is my mouse cursor. There is no transition yet, and the little text saying "View more details" has been removed. It seemed to miss the mark UX-wise, but I still wanted to keep some "haptic" feedback for the user.

Screenshot from 2019-10-22 19-09-48

### CODE REVIEW

**Comment by zacharyjarnagin** [comment]
So I added a CSS rule to transition smoothly. Feel free to tweak it. I think making the shadows stand out a tiny bit more might help but I am not a UX/UI/Seeing with my eyes person.

**Comment by lukesanantonio** [comment]
@zacharyjarnagin Thanks so much for working on this. I made the transition time a little faster, and made the shadow larger. Let me know what you think!

**Comment by zacharyjarnagin** [comment]
Looks good to me!

**Comment by lukesanantonio** [comment]
@zacharyjarnagin Feel free to review it (approve / request changes / comment). When Jaedyn gives it the green light I'll merge.

**Pull request merged**
